/// Flutter icons Dison
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Dison
///      fonts:
///       - asset: fonts/Dison.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Dison {
  Dison._();

  static const _kFontFam = 'Dison';
  static const _kFontPkg = null;

  static const IconData location = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
